/**
 * Created by gjbelang on 3/7/14.
 */
var evApp = angular.module('evApp',[]).
    config(function($routeProvider) {
        $routeProvider.
            when('/',{
                    controller: 'SimpleController',
                    templateUrl:'app/partials/main.html'
                })
            .when('/bookstudy',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/bookstudy.html'
                })
            .when('/caregiver',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/caregiver.html'
                })
            .when('/resources',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/resources.html'
                })
            .when('/contact',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/contact.html'
                })
            .when('/creating_work_you_love',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/cwyl.html'
                })
            .when('/ebook',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/ebook.html'
                })
            .when('/ebook_video',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/ebook_video.html'
                })
            .when('/faq',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/faq.html'
                })
            .when('/404',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/404.html'
                })
            .when('/publications',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/publication.html'
                })
            .when('/workshops',
                {
                    controller:'SimpleController',
                    templateUrl:'/app/partials/ws.html'
                })
            .when('/testimonials',
                {
                    controller:'SimpleController',
                    templateUrl:'app/partials/testimonials.html'
                })
            .when('/newsletter',
                {
                    templateUrl:'app/partials/newsletter.html'
                })
            .when('/speaking_engagements',
                {
                    templateUrl:'app/partials/speaking.html'
                })
            .when('/paypal',
                {
                    templateUrl:'app/partials/paypal.html'
                })
            .when('/successfully_managing_personal_life_transitions',
                {
                    templateUrl:'app/partials/smplt.html'
                })
            .otherwise({ redirectTo: '/404'});
});